language: node_js
os: linux
sudo: required
dist: trusty
group: travis_lts
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - xvfb
addons:
  chrome: stable
node_js:
  - '10'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - npm install

env:
  - CXX=g++-4.8

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - ken.martin@kitware.com
      - matt.mccormick@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - doc/build-tmp

script:
  - npm install
  - npm run build:release
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/itk-vtk-viewer.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
